public enum ApplicationProgressStatus
{
    ACADEMIC_RECORDS = 1,
    REQUIRED_DOCUMENT = 2,
    PROOF_OF_PAYMENT = 3,
    LETTER_ACCEPTANCE_OF_LEARNER_OF_CODE_OF_CONDUCT = 4,
    REGISTRATION_LETTER = 5,
    ACTIVITY_NOTIFICATION = 6,
    MODULE_ACTIVITY_REPORT = 9,
    NEW_STAFF_MEMBER = 7
}

public enum UploadLetter
{
    REGISTRATION_LETTER_UPLOAD_ID = 24,
    LETTER_ACCEPTANCE_OF_LEARNER_OF_CODE_OF_CONDUCT_UPLOAD_ID = 25
}